services:
  web:
    build: ./test_task_config
    image: test_task_web
    command: ["gunicorn", "test_task_config.wsgi:application", "--bind", "0.0.0.0:8080"]
    volumes:
      - ./test_task_config/:/usr/src/app/
    env_file:
      - env.dev
    depends_on:
      - db
  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env.db
    ports:
      - "5432:5432"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
     driver: local