name: CI Build Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start database
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d db
          
      - name: Start web container
        run: docker compose -f docker-compose.yml up -d web

      - name: Test health endpoint
        run: |
          sleep 5
          curl --fail http://localhost:8080/health/

      - name: Teardown
        run: docker compose -f docker-compose.yml down
